runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  secure: never
  static_files: dist/hello-doctor/index.html
  upload: dist/hello-doctor/index.html
- url: /
  static_dir: dist/hello-doctor
  secure: never